// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::ffi;
use glib::{prelude::*, translate::*};

glib::wrapper! {
    #[doc(alias = "GdkWaylandSurface")]
    pub struct WaylandSurface(Object<ffi::GdkWaylandSurface>) @extends gdk::Surface;

    match fn {
        type_ => || ffi::gdk_wayland_surface_get_type(),
    }
}

impl WaylandSurface {
    pub const NONE: Option<&'static WaylandSurface> = None;

    #[doc(alias = "gdk_wayland_surface_force_next_commit")]
    pub fn force_next_commit(surface: &impl IsA<gdk::Surface>) {
        assert_initialized_main_thread!();
        unsafe {
            ffi::gdk_wayland_surface_force_next_commit(surface.as_ref().to_glib_none().0);
        }
    }
}
