name: Trigger PR on Merge from External Repo

on:
  repository_dispatch:
    types: [gir-files-merge-event]

jobs:
  trigger-python-script:
    if: ${{ github.event.workflow_run.actor == 'github-actions[bot]' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          submodules: true
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Git submodules
        run: |
          git submodule update --remote
          git add .
          git diff --cached --exit-code || git commit -m "Update gir/gir-files"

      - name: Run Python script to generate changes
        run: python generate.py
      - name: Commit and push changes
        run: |
          python ./generate.py
          git add .
          git diff --exit-code || git commit -m "Auto-generated changes from external repo merge"
          git push origin "auto-pr-branch" || echo "Branch already exists"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "auto-pr-branch"
          title: "Automated PR: Changes from updating gir/gir-files"
          body: "This PR contains auto-generated changes after a merge in the external gir-files repository."
          commit-message: "Auto-generated changes from updating gir/gir-files"
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
